### ISSUE TITLE
Path deletion isn't working after Article deletion

### ISSUE THREAD

**Issue by thomasduenser** [sulu/SuluArticleBundle#102]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no

#### Actual Behavior

When an article gets deleted, the related path inside `ro_routes` isn't deleted.

#### Expected Behavior

The path to the deleted article should be deleted as well.

#### Steps to Reproduce

1. Create an article named `test`
2. Check `ro_routes` table, the generate `path` should be `/test`
3. Delete this article
4. Create a new article named `test`
5. `path` is now `/test-1` because the old `path`hasn't been deleted

**Comment by wachterjohannes** [comment]
should be fixed with #111
