### ISSUE TITLE
Teaser-Selection list: missing locale as url parameter

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/SuluArticleBundle#105]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | none
| Browser Version | none

#### Actual Behavior

Currently the complete `teaser-selection/list@sulucontent` was copied to this bundle to add a locale parameter.

#### Expected Behavior

This file should not be copied to the bundle it should be handled correctly in sulu.

**Comment by wachterjohannes** [comment]
will be fixed in https://github.com/sulu/sulu/pull/3266 and released with `1.6.0`

**Comment by danrot** [comment]
Fixed in sulu/sulu#3266
