### ISSUE TITLE
Article data-provider data-source

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/SuluArticleBundle#12]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | cec35da |
| Browser Version | none |
#### Expected Behavior

The `ArticleDataProvider`should provide a data-source with a selection of the type.

**Comment by trickreich** [comment]
@wachterjohannes is this issue still open?

**Comment by wachterjohannes** [comment]
yes you should be able to select the type in data-source.

**Comment by wachterjohannes** [comment]
the PR #62 adds the ability to filter for mutliple types. The datasource could be used to make this configurable for content-manager via a datagrid of all types with multiple selection.
