### ISSUE TITLE
Export of articles as csv

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluArticleBundle#120]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.5
| Article Version | 0.3

### Actual Behavior

CSV Export is currently not available

### Expected Behavior

Export should be added to articles.

### Steps to Reproduce

The list view should have a export function.

### Possible Solutions

Add basic sulu csv export function.

**Comment by wachterjohannes** [comment]
i have tried to implement this - but the problem is a performance thing. we would have to load the whole data from elasticsearch (tested with 2000 articles) which is quite heavy and fails currently without a message. this feature should be moved to a later release.

**Comment by niklasnatter** [comment]
Thanks for reporting! I just tested this with Sulu 2.2.3 and SuluArticleBundle 2.2.2. Looks like this was implemented in some recent release, therefore I am going to close this.
