### ISSUE TITLE
Reindex command doesn't work correct for different locales

### ISSUE THREAD

**Issue by thomasduenser** [sulu/SuluArticleBundle#135]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | 0.3.*

#### Actual Behavior

I have multiple languages and an `ArticleIndexListener` that adds some properties to the custom `ArticleViewDocument`. The articles only exist in `de`!

When using the reindex command like this:
```
app/webconsole sulu:article:index-rebuild en --live -e prod
app/webconsole sulu:article:index-rebuild de --live -e prod
```

Everything works fine. When the order of the commands is switched (first `de`, then `en`), it overwrites the `de` values with the `en` values.

#### Expected Behavior

As the `uuid` consists of the page uuid and the locale, I expect to receive the correct view document in my listener.

#### Steps to Reproduce

1. Install bundle with a version of `0.3.*`
2. Crate article in `de` but not in `en`
3. Create custom view document with a new property
4. Create an index listener and set the new property
5. Execute the reindex command first with `de` then `en` and check the index

**Comment by trickreich** [comment]
Maybe it would be nice if the command reindex all available Sulu locales when no locale is provided.
Also a documentation for this command.

**Comment by trickreich** [comment]
In my opinion the reindex command should run for both workspaces (default and live) per default.
