### ISSUE TITLE
Why is this bundle using a dead version of Guzzle?

### ISSUE THREAD

**Issue by Swader** [sulu/SuluArticleBundle#181]
During installation, it's clearly stated that guzzle/guzzle is abandoned. Why does this bundle still use it instead of something like httplug for abstraction?

<img width="695" alt="screenshot 2017-06-07 11 36 44" src="https://user-images.githubusercontent.com/1430603/26872163-e1fe625e-4b75-11e7-8712-7cd84fd5b798.png">

**Comment by wachterjohannes** [comment]
without a deeper look this problem is inherited from `sulu/sulu` where we use the `cboden/ratchet:0.3.*` and `friendsofsymfony/http-cache:1.4.*` we are not using it activly in this bundle.

I will close this issue - please reopen it if you think this is not answer enough :)
