### ISSUE TITLE
When copying an existing article into a new locale, the article is both published and draft

### ISSUE THREAD

**Issue by Swader** [sulu/SuluArticleBundle#185]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 0.5.1
| Sulu Version | 1.6.0-RC1

#### Actual Behavior

The article that is copied from an existing locale is both in draft mode and marked as published.

#### Expected Behavior

It should be only one of those things, preferably draft.

#### Steps to Reproduce

Write article in locale1. Switch to locale2 and pick to copy content from existing locale.

<img width="971" alt="screenshot 2017-06-07 17 52 23" src="https://user-images.githubusercontent.com/1430603/26888266-c5c32888-4baa-11e7-964e-cfaed14e7ee0.png">

**Comment by danrot** [comment]
@wachterjohannes Is #3555 enough for that to be fixed?

**Comment by wachterjohannes** [comment]
yes :)
