### ISSUE TITLE
When building with --destroy, the ES index is not rebuilt

### ISSUE THREAD

**Issue by Swader** [sulu/SuluArticleBundle#198]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | All
| Sulu Version | All

#### Actual Behavior

If you execute `bin/adminconsole sulu:build --destroy`, the ES index remains. This leaves behind artifacts in `/admin` which lead to non-existing articles.

<img width="919" alt="screenshot 2017-06-15 11 58 39" src="https://user-images.githubusercontent.com/1430603/27177008-37cb1c18-51c5-11e7-8b0c-021de2fec68c.png">

#### Expected Behavior

If the database is *destroyed* its indexes should be, too.

#### Steps to Reproduce

- Have articles.
- Issue a rebuild with destroy.
- Notice orphaned links in /admin.

#### Possible Solutions

Extend the `sulu:build` command to execute a recreation of the index if `--destroy` was passed in.

**Comment by wachterjohannes** [comment]
I can confirm this issue. We have to add a new `ArticleIndexBuilder` which will be called in this case.
