### ISSUE TITLE
Typo in installation.md

### ISSUE THREAD

**Issue by vmeijer** [sulu/SuluArticleBundle#201]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| SuluArticleBundle Version | master
| Sulu Version | n/a

#### Actual Behavior

Just a small typo in https://github.com/sulu/SuluArticleBundle/blob/master/Resources/doc/installation.md

It says `sulu_arictle_api` but I think `sulu_article_api` is meant.

**Comment by wachterjohannes** [comment]
fixed with #202
