### ISSUE TITLE
Index articles properly in Massive Search

### ISSUE THREAD

**Issue by matt-halliday** [sulu/SuluArticleBundle#226]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | yes
| SuluArticleBundle Version | 0.6.1
| Sulu Version | 1.6.1

#### Actual Behavior

Articles are indexed in Massive search in non-published/live but not in published/live. Index: `article`

#### Expected Behavior

Live/Published articles should be indexed properly. Index: `article_published`

#### Steps to Reproduce

Sulu Minimal with Article Bundle. Extend `WebsiteSearchController` to include the articles index:

```
$hits = $this->searchManager
            ->createSearch($this->generateQueryString($query))
            ->locale($locale)
            ->indexes(['page_' . $webspace->getKey() . '_published', 'article'])
            ->execute();
```

I'm using MassisveSearch with elasticsearch 5.x but I think the issue is also affecting the zend filebased indexing too.

It would be great if the indexes searched by the website controller could be added to via config but this is probably more of an issue for the main bundle. Something in the config like:

```
sulu_search:
      indexes:
            - 'page_%webspace_key%_published' # default
            - 'article_live'
```

This would prevent extending the whole controller just to add an index.

**Comment by wachterjohannes** [comment]
I have found the issue here https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php#L136

When a different `index_name` as `page` is set the `_published` postfix is not used.
