### ISSUE TITLE
Add parameters to filter articles by type in article_selection content type

### ISSUE THREAD

**Issue by matt-halliday** [sulu/SuluArticleBundle#232]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| SuluArticleBundle Version | 0.6.1
| Sulu Version | 1.6.2

#### Actual Behavior

When selecting articles via direct assignment with content type `article_selection` you can't filter available articles by type. No parameters exist for this content type.

#### Expected Behavior

Articles can be restricted to certain types when making selection via a parameter:

```
<property name="article" type="article_selection">
  <meta>
    <title lang="en">Article</title>
  </meta>

  <params>
    <param name="types">
      <param name="news"/>
    </param>
  </params>
</property>
```

And/Or, in keeping with current documentation for `smart_content`

```
<property name="article" type="article_selection">
  <meta>
    <title lang="en">Article</title>
  </meta>

  <params>
    <param name="types" value="news," />
  </params>
</property>
```

**Comment by niklasnatter** [comment]
Thanks for reporting! I just tested this with Sulu 2.2.3 and SuluArticleBundle 2.2.2. The following configuration works for me, therefore i am going to close this 🙂 

```xml
<property name="article" type="article_selection">
    <meta>
        <title lang="en">Article</title>
    </meta>

    <params>
        <param name="types" value="other" />
    </params>
</property>
```
