### ISSUE TITLE
Internal link in the wysiwyg editor to an article returns as invalid

### ISSUE THREAD

**Issue by marcoranter** [sulu/SuluArticleBundle#250]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 0.5
| Sulu Version | 1.5

#### Actual Behavior

Internal links in the wysiwyg editor to an article returns as invalid and is not editable

#### Expected Behavior

The internal link should return as a valid link and you should be able to edit it afterwards

#### Steps to Reproduce

1. In the wysiwyg editor create an internal link to an article
2. Save and refresh the page and navigate to the wysiwyg editor
3. The field should say it has an invalid link
![invalid-link](https://user-images.githubusercontent.com/31700126/30150114-7ef7cbf0-93aa-11e7-8f20-29a5a395fe1c.png)
4. When trying to edit the link a loading icon appears, but it doesn't load properly

**Comment by wachterjohannes** [comment]
@marcoranter I have released this fix in the releases `0.5.3` and `0.6.3`

**Comment by marcoranter** [comment]
@wachterjohannes Thanks for the fast response and support!
