### ISSUE TITLE
Catch ElasticSearch exceptions instead of throwing them in production

### ISSUE THREAD

**Issue by matt-halliday** [sulu/SuluArticleBundle#252]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| SuluArticleBundle Version | 0.7.0
| Sulu Version | 1.6.4

#### Actual Behavior

When there is an issue with the elasticsearch service which results in an exception being thrown, the page error 500s, taking down the whole site.

#### Expected Behavior

When there is an issue with the elasticsearch service in production environments, the exception should be logged and the search query should return null so that the rest of the site is still in operation.

#### Steps to Reproduce

Misconfigure elasticsearch parameters in production or turn the service off.

#### Possible Solutions

I had thought that a possible idea would be to dispatch an event when elastic search exceptions occur. This event could be handled by a listener that in dev/stage environments simply throws the exception, but in production has some logging and returns null. The rationale behind a listener/event implementation would be that it could easily be overwritten with custom error handling if needed. It could also be utilised in the main sulu bundle where elasticsearch maybe used for search results.

**Comment by wachterjohannes** [comment]
@matt-halliday we have decided to not handle this exceptions. the reason is that there is no "correct" way for this. we see elasticsearch as a hard dependency for the application like mysql which also will bring the application to crash if it is not there.
