### ISSUE TITLE
Deleting article does not remove article from elasticsearch.

### ISSUE THREAD

**Issue by dominikmatt** [sulu/SuluArticleBundle#259]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 0.7.0
| Sulu Version | dev-master

#### Actual Behavior

Deleting article does not remove article from elasticsearch.

#### Steps to Reproduce

- Create a new article.
- Delete it.
- Reload list. (Article always stays in list but cannot load content.)

#### Possible Solutions

`bin/websiteconsole sulu:article:index-rebuild de --clear`

**Comment by wachterjohannes** [comment]
the problem was fixed by recreating the index with the correct mapping.
