### ISSUE TITLE
Ability to filter articles in CMS by XML page template (in addition to article type as it is now)

### ISSUE THREAD

**Issue by Edvinas9** [sulu/SuluArticleBundle#265]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| SuluArticleBundle Version | 0.7.1
| Sulu Version | 1.6.5

#### Actual Behavior

In the Articles management section in the CMS it is possible to filter articles by article type using tab navigation.

#### Expected Behavior

Since article types can have multiple XML page templates - it would be nice to have an option to apply additional filter to show articles with specific article type + XML template combination only.

#### Possible Solutions

Add another filter tool here which shows all XML templates within article type so you can select which one you want to see.
![image](https://user-images.githubusercontent.com/2161759/31492662-fa3257ea-af43-11e7-9ca2-0d88cd69c4b0.png)

**Comment by wachterjohannes** [comment]
nice idea! the template dropdown has to be changed when changing the article-type

**Comment by niklasnatter** [comment]
Version 2 of the bundle does not provide filters like this anymore, therefore i am going to close this. Thanks for reporting!
