### ISSUE TITLE
PHPStan currently only on level 1

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluArticleBundle#279]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 1.0.0-RC2
| Sulu Version | 1.6.7

#### Actual Behavior

Currently phpstan is only run on level 1

#### Expected Behavior

There are some issues which should be solved. Also the PHPCR migrations are excluded in the stan configuration.

#### Steps to Reproduce

Run phpstan on --level 2 or higher

#### Possible Solutions

Solve the issues.

**Comment by niklasnatter** [comment]
Fixed by #454
