### ISSUE TITLE
Version conflict FOSRest when using latest sulu dev version with article dev version

### ISSUE THREAD

**Issue by stijndm** [sulu/SuluArticleBundle#298]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 1275640a6d7c830a7331579b268019b8d8b605e6 (dev branch)
| Sulu Version | aaf6c2571937d76361786419408b48943ec5fd87 (dev branch)

#### Actual Behavior

When in the admin on the article overview, clicking an article title to edit the article does nothing (API request in the background returns 500 internal error)

#### Expected Behavior

Edit form for the required article is displayed

#### Steps to Reproduce

Go to article overview, click on article title or pencil icon.

#### Possible Solutions

There seems to be a conflict in versions where Sulu is already running FOS 2.2 and SuluArticleBundle still expects 1.x.

It should be sufficient to to follow the upgrade instructions outlined at https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/UPGRADING-2.0.md. More specifically refactoring "setSerializationContext" in ArticleController.php.

I'm currently unsure if other changes are needed. Since I need this fixed rather soon I'll most likely have a look at it this week.

**Comment by wachterjohannes** [comment]
@stijndm sorry for the late delay. the develop branch of sulu is far away from master branch (sulu-admin rewrite) - we will update this bundle to sulu 2.0 when everything is clear there.

**Comment by stijndm** [comment]
No worries. For now I forked the bundle and fixed it at https://github.com/Nascom/SuluArticleBundle/commit/535487fd5095cf229253f83073964afdf174ced1

**Comment by niklasnatter** [comment]
Not sure when this was fixed, but the bundle is compatible with new version of the `FOSRestBundle` now. Thanks for reporting!
