### ISSUE TITLE
Elasticsearch ^6.0 compatibility

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/SuluArticleBundle#304]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| SuluArticleBundle Version | all
| Sulu Version | ^1.6

#### Actual Behavior

ongr-io/ElasticsearchBundle ~~does not support PHP `^7.2` (https://github.com/ongr-io/ElasticsearchBundle/issues/832)~~ and elasticsearch `^6.0` (https://github.com/ongr-io/ElasticsearchBundle/issues/828)

#### Expected Behavior

This should be supported.

#### Possible Solutions

* Remove dependency to ongr-io/ElasticsearchBundle (rewrite of indexing - e.g. using raw elasticsearch library)
* Find a better solution for the performance problems and remove elasticsearch dependency

**Comment by mareksuscak** [comment]
What's the current status? I'm a little confused because according to [this comment](https://github.com/ongr-io/ElasticsearchBundle/issues/828#issuecomment-451946214) the issue got resolved in ElasticsearchBundle 5.2.0 but despite having installed version 5.2.4 and SuluArticleBundle 1.0.1, I'm still seeing weird autoloading errors.

**Comment by wachterjohannes** [comment]
@mareksuscak this issue is only resolved partly - the bundle is now ready for 7.2 but not ES 6.0

**Comment by mareksuscak** [comment]
Which version is ready for PHP 7.2 though? The latest one (i.e. 1.0.1)? Or the development version that's not been released yet? 1.0.1 didn't work w/ PHP 7.2 and Elasticsearch server 5.x.

**Comment by wachterjohannes** [comment]
all versions ^1.0 should be ready for php 7.2 and ES ^5.0 - what is you exact problem? do you have any error message?

**Comment by mareksuscak** [comment]
There was a problem w/ the autoloader. Specifically, it was looking for `Object` class in [this file](https://github.com/ongr-io/ElasticsearchBundle/blob/master/Annotation/Object.php) and said the file was there but the class was not found.

**Comment by YetiCGN** [comment]
@mareksuscak I think you need to use the new annotation `@ObjectType` instead of `@Object` in your own code.

**Comment by mareksuscak** [comment]
We don't use that annotation in our own code. Just tried it again w/ the same result. However, upon manually removing the contents of the cache folder, it started working. I'm pretty sure I ran `cache:clear` command before.

**Comment by alexander-schranz** [comment]
@mareksuscak when working with sulu you should keep in mind there are 2 Kernels (Admin and Website) which has there own caches to clear them use:

```php
bin/adminconsole cache:clear       
bin/websiteconsole cache:clear

# make also sure you provide the correct environment to each ocmmand using e.g.: --env prod
```

or the evil way:

```bash
rm -rf var/cache/*
```

**Comment by YetiCGN** [comment]
I don't think that's evil at all, I always do it the `rm -rf` way. Much faster and more thorough. 😉

**Comment by mareksuscak** [comment]
@alexander-schranz I am aware of that. That's the thing. I always clear both. And it should not even be necessary in `dev` env, no?

**Comment by alexander-schranz** [comment]
@mareksuscak there are only a few things which don't need cache clear on dev but there are also many things e.g. routes and compilerpass values which need also a clear cache on dev.

**Comment by jaswanthjinni** [comment]
Cannot use 'Object' as class name as it is reserved 
is their any solution for this ?

**Comment by alexander-schranz** [comment]
@jaswanthjinni 

> Cannot use 'Object' as class name as it is reserved
> is their any solution for this ?

which version of the `Ongr/ElasticsearchBundle` are you using this should be fixed some time ago in there bundle.

> composer info ongr/elasticsearch-bundle | grep version

**Comment by jaswanthjinni** [comment]
i am using php 7.2 with yii 2.0.14 and i am working on ubantu 20.04 version

**Comment by alexander-schranz** [comment]
ES 6 support was some time ago merged. ES 7 support is coming soon. See #433
