### ISSUE TITLE
Error Occures when including master.html.twig

### ISSUE THREAD

**Issue by C-burr** [sulu/SuluArticleBundle#307]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | ^0.7.1
| Sulu Version | 1.6.14

#### Actual Behavior

When creating an article and extending the master (which includes meta.html.twig), the following error occures: 
An exception has been thrown during the rendering of a template ("Invalid path '/cmf/'").

Normal pages work fine, its only the articles that dont work. 

#### Expected Behavior

No error should come up.

#### Steps to Reproduce

Install articlebundle and create article, extend master.html.twig.
Since the master includes the meta.html.twig by default, this error occures.

#### Possible Solutions

Disable Default snippets by adding the following lines to your config.yml:

sulu_snippet:
    types:
        snippet:
            default_enabled: false

**Comment by alexander-schranz** [comment]
should be fixed with #308
