### ISSUE TITLE
How to get author information from author id?

### ISSUE THREAD

**Issue by devkruu** [sulu/SuluArticleBundle#315]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| SuluArticleBundle Version | 1.0.0-RC5
| Sulu Version | 1.6.14

In an ArticleDocument the author is an int with the authorId. How do I get for example the full name from the integer in a twig template?

**Comment by niklasnatter** [comment]
As already said, using the [`sulu_resolve_user` function](https://docs.sulu.io/en/latest/reference/twig-extensions/functions/sulu_resolve_user.html) in twig is the right approach here 🙂
