### ISSUE TITLE
Upgrading ONGR/ElasticSearchBundle breaks ArticleViewDocument

### ISSUE THREAD

**Issue by DavidFeller** [sulu/SuluArticleBundle#320]
| Q | A
| --- | ---
| Bug? | ?
| New Feature? | no
| SuluArticleBundle Version | 0.7.1
| Sulu Version | 1.6.16

#### Actual Behavior

How does Sulu behave at the moment? 
![ongr-elasticsearchbundle-5 0 6](https://user-images.githubusercontent.com/2094727/39043624-2ae9cfd2-448e-11e8-9d9a-d377932d8fca.png)

#### Steps to Reproduce

Upgrade ongr/elasticsearch-bundle to version 5.0.6

#### Possible Solutions

Downgrade ongr/elasticsearch-bundle to version 5.0.5 or lower

**Comment by alexander-schranz** [comment]
I think this change was done in the ongr/elasticsearch-bundle as it seems not make any problems with the our current own fork of it [handcraftedinthealps/elasticsearchbundle](https://github.com/handcraftedinthealps/elasticsearchbundle). Let us know if still errors appear in this case. Please make sure before that you updated both the article bundle and elasticsearch bundle to the newest version of your used major version.
