### ISSUE TITLE
Adding images inline using the texteditor

### ISSUE THREAD

**Issue by alejandrofloresm** [sulu/SuluArticleBundle#324]
| Q | A
| --- | ---
| New Feature? | Probably
| SuluArticleBundle Version | 0.7.1
| Sulu Version | 1.6.0

#### Actual Behavior

When I click on the editor "Add Image" it adds the image as a link.

#### Expected Behavior

The image should be added as an <img> tag and not as an anchor to an image.

**Comment by niklasnatter** [comment]
Thanks for reporting - Sulu does not allow to insert images via the text editor intentionally. See the following blog post: 

> For example, sometimes people ask us how to insert an image using the WYSIWYG editor in Sulu, but this is contrary to our structured-content approach. Inserting images using the editor means they are not single-sourced. This makes it difficult, for example, for a developer to resize images for different devices or make a gallery out of all the images in an article.

https://sulu.io/guides/structured-content-with-blocks
