### ISSUE TITLE
Publish on ArticlePageDocuments don't on published documents

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluArticleBundle#325]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 1.0.0-RC6
| Sulu Version | 1.6.18

#### Actual Behavior

When you have a multipage article which is published and try to save and publish on e.g. Page 2 it fails with a ResourceLocatorAlreadyExistsException.

#### Expected Behavior

It should be possible to publish the page on every document not only on the Page 1.

#### Steps to Reproduce

1. create a multipage article
2. publish the multipage article
3. go to page 2 or further
4. try to save and publish

**Comment by niklasnatter** [comment]
Version 2 of the bundle does not support multi-page articles anymore (https://github.com/sulu/SuluArticleBundle/issues/407). Therefore, I am going to close this issue 🙂
