### ISSUE TITLE
Unable to access content on ArticleViewDocument with SmartContent

### ISSUE THREAD

**Issue by C-burr** [sulu/SuluArticleBundle#327]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 1.0.0-RC5
| Sulu Version | 1.6.18

#### Actual Behavior

Cannot access content of ArticleViewDocument when adding content type smart_content with provider value="articles" to a block type in the article. (Might also happen if smart_content is not inside a block type or if provider is set differently, i did not test this).

The following error occurs, even though it is not very insightful: 
```Unexpected RuntimeException thrown from a caster: Document has not been applied to structure yet, cannot retrieve data from structure.```

#### Expected Behavior

Should be able to access "content" and "view" of article.

#### Steps to Reproduce

create an article_selection on a page, try to access "content" or "view" of a single article.
The article must include a block type with smart_content.

**Comment by sfaujour** [comment]
Version 0.7.1 has already the same "bug".

**Comment by niklasnatter** [comment]
Thanks for reporting! I just tested this with Sulu 2.2.2, SuluArticleBundle 2.2.2 and the following property:

```xml
<property name="articles" type="smart_content">
    <meta>
        <title lang="en">Articles</title>
        <title lang="de">Artikel</title>
    </meta>

    <params>
        <param name="provider" value="articles"/>
    </params>
</property>
```

I am able to access the information in my template like this:

```twig
{{ dump(content.articles) }}
{{ dump(content.articles[0].content.content.title) }}
{{ dump(content.articles[0].content.view.title) }}
```

I think this was fixed in some recent version. Therefore I am going to close it 🙂
