### ISSUE TITLE
Webspace selection does not update preview

### ISSUE THREAD

**Issue by C-burr** [sulu/SuluArticleBundle#359]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 1.0.0-RC4
| Sulu Version | 1.6.9

#### Actual Behavior

When choosing the webspace while editing an article, the preview window does not update with the correct webspace.

#### Expected Behavior

The Template is displayed as it is available in the selected webspace.

#### Steps to Reproduce

Create two webspaces, with an article template that only exists in the secondary webspace. While editing the article, the preview window will show up with an error that the template does not exist, which is expected since the wrong webspace is selected by default. Switching to the correct webspace should resolve this but the preview window does not update.

#### Possible Solutions

In `PreviewMessageHandler.php` in the function `start` set the previewToken and the locale before rendering like this:

before:
```
        $response = $this->preview->render($token, $message['webspaceKey'], $message['locale']);

        $context->set('previewToken', $token);
        $context->set('locale', $message['locale']);
``` 

after: 
```
        $context->set('previewToken', $token);
        $context->set('locale', $message['locale']);

        $response = $this->preview->render($token, $message['webspaceKey'], $message['locale']);
```

**Comment by wachterjohannes** [comment]
@C-burr this is already added to Sulu a few month ago (Tag 1.6.15) see https://github.com/sulu/sulu/releases/tag/1.6.15
