### ISSUE TITLE
Missing properties for minOccurs and maxOccurs in article_selection 

### ISSUE THREAD

**Issue by ivanmilosavljevic** [sulu/SuluArticleBundle#367]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| SuluArticleBundle Version | "version": "1.0.0-RC7"
| Sulu Version | "version": "1.6.22"

#### Actual Behavior

Sulu admin panel doesn't allow selection of articles.

#### Expected Behavior

I want to be able to select a maximum of three articles.

#### Steps to Reproduce

Configuration of article_selection:
```xml
<property name="articles" type="article_selection" minOccurs="1" maxOccurs="3">
    <meta>
        <title lang="en">Das könnte Sie auch interessieren</title>
        <title lang="en">You may be interested in</title>
    </meta>
</property>
```

**Comment by niklasnatter** [comment]
Thanks for reporting - should be fixed by https://github.com/sulu/sulu/pull/5666. This should be configurable via the `min` and `max` parameter in Sulu 2.3:

```xml
<property name="articles" type="article_selection">
    <params>
        <param name="min" value="1"/>
        <param name="max" value="3"/>
    </params>
</property>
```
