### ISSUE TITLE
Add AutomationBundle again to test requirements

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluArticleBundle#398]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| SuluArticleBundle Version | 2.0
| Sulu Version | 2.0

#### Actual Behavior

The compatibility to the SuluAutomationBundle is not tested because it was removed in  #396 because the AutomationBundle was at that time not yet 2.0 compatible.

#### Expected Behavior

As soon as the SuluAutomationBundle is 2.0 compatible it should added again (sulu/SuluAutomationBundle#22)

**Comment by niklasnatter** [comment]
Fixed by https://github.com/sulu/SuluArticleBundle/pull/412
