### ISSUE TITLE
Save button not disabled after saving with special characters

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluArticleBundle#404]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | dev-develop (pre 2.0)
| Sulu Version | 2.0

#### Actual Behavior

Save button not disabled after saving with special characters

#### Expected Behavior

After saving the save button should not be dirty.

#### Steps to Reproduce

Add a text to a text editor field which have a special character e.g.:

> We've been there.

When saving this text the special character seems to be returned different then it is send. So mobx does set the form again to be dirty.

#### Possible Solutions

Not sure, need to debug who is changing the properties encoding.

**Comment by niklasnatter** [comment]
Thanks for reporting! I just tested this with Sulu 2.2.3 and SuluArticleBundle 2.2.2. Looks like this is not an issue anymore, therefore I am going to close this.
