### ISSUE TITLE
Wrong template name article in developer documentation

### ISSUE THREAD

**Issue by almare** [sulu/SuluArticleBundle#408]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | developer version
| Sulu Version | 2.0

#### Actual Behavior

If I follow the the developer documentation I am not able to install the ArticleBundle.

#### Expected Behavior

The bundle should be installable if i follow the documentation 

#### Steps to Reproduce

Follow documentation and try to run
```
bin/console sulu:document:init
```

#### Possible Solutions

Change the docu from 
```
%kernel.project_dir%/config/templates/articles/article.xml
%kernel.project_dir%/templates/articles/article.html.twig
```
to
```
%kernel.project_dir%/config/templates/articles/default.xml
%kernel.project_dir%/templates/articles/default.html.twig
```

**Comment by nnatter** [comment]
I think this should be fixed. Thanks for reporting!
