### ISSUE TITLE
Can't delete articles in Sulu 2.0

### ISSUE THREAD

**Issue by almare** [sulu/SuluArticleBundle#409]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | developer version
| Sulu Version | 2.0

#### Actual Behavior

Added articles can't be deleted.
Could not find document with ID or path "49396c20-0dd8-472d-9f33-62042f7244ad"

#### Expected Behavior

The articles should be deletable inside admin view.  

#### Steps to Reproduce

Add article and try to delete them.

**Comment by almare** [comment]
`message	{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [su_articles_live]","resource.type":"index_or_alias","resource.id":"su_articles_live","index_uuid":"_na_","index":"su_articles_live"}],"type":"index_not_found_exception","reason":"no such index [su_articles_live]","resource.type":"index_or_alias","resource.id":"su_articles_live","index_uuid":"_na_","index":"su_articles_live"},"status":404}`

Is elasticsearch a hard requirement to get it working? I ask due tu the bug with elasticsearch 6.0?

**Comment by alexander-schranz** [comment]
@almare Sorry for the late response!

As mentioned in the Readme Elasticsearch is a hard requirement (see also [here](https://github.com/sulu/SuluArticleBundle/issues/430#issuecomment-580147993)).

Currently its not yet possible to use elasticsearch 7 see #431. Currently if you want to install SuluArticleBundle you need to use Elasticsearch 6.

So try please the following:

```json
        "elasticsearch/elasticsearch": "^6.5",
        "ongr/elasticsearch-bundle": "^5.2@dev",
        "sulu/article-bundle": "^2.0@dev",
```

And use ES6 as endpoint.

**Comment by almare** [comment]
@alexander-schranz Thank you for your explanation.

I don't have generally a problem with elasticsearch. This is from my point of view the right decision, even for small sites. All my projects use es, my problem is I don't want to maintain different versions / instances of es on the same webserver. That's basically all (maybe because of I never tried before). 
I just hope sulu will get es 7 support :-) and I am fine

**Comment by almare** [comment]
The issue is indeed based on the wrong es version. After a downgrade the articles could be deleted. I will close this issue for this reason. Thank you for your support.
