### ISSUE TITLE
Sulu 2.0 - I can't select a specific article type in smart content.

### ISSUE THREAD

**Issue by Joana222** [sulu/SuluArticleBundle#413]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0
| Sulu Article Version | pre 2.0 (dev-develop)
| Browser Version | everywhere

#### Actual Behavior

All articles are shown automatically in smart content. 

#### Expected Behavior

Only one specific article type should be shown. 

#### Steps to Reproduce

```xml
<property name="articles" type="smart_content">
       <meta>
              <title lang="de">Smart Content Artikel</title>
              <title lang="en">Smart Content Articles</title>
        </meta>

        <params>
               <param name="provider" value="articles"/>
               <param name="types" value="press"/>
        </params>
</property>
```

**Comment by danrot** [comment]
Fixed by #4913
