### ISSUE TITLE
How to unpublish articles?

### ISSUE THREAD

**Issue by almare** [sulu/SuluArticleBundle#437]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | maybe?
| SuluArticleBundle Version | dev-develop
| Sulu Version | Specific version or SHA of a commit

#### Actual Behavior

At the moment it is not clearhow to unpublish a article. There is no unpublish button

#### Expected Behavior

Provide a unpublish button for articles

#### Steps to Reproduce

Add article click save. Reload article. Save button is disabled and even after changing anything the save button dropdown doesn't provide a unpublish button. 
#### Possible Solutions

Ideally there would be a unpublish button like the publish button.
![article-bundle-bug](https://user-images.githubusercontent.com/12784601/75421806-61625c00-593b-11ea-9ca3-633c1fefeca5.png)
![sulu-article-bug-save-button](https://user-images.githubusercontent.com/12784601/75421824-69ba9700-593b-11ea-82af-f53a74010ac0.png)

**Comment by nnatter** [comment]
I think this should be fixed by https://github.com/sulu/SuluArticleBundle/pull/438

**Comment by almare** [comment]
Thank you for the feedback

**Comment by almare** [comment]
Will this also fixed for 2.0 branch. Currently it looks like it's only fixed for 1.6.8

**Comment by nnatter** [comment]
Hey, 
what do you mean with development branch for 2.0? 
The pull request referenced above was merged into the `develop` branch. That branch should be compatible with Sulu 2.0.

**Comment by almare** [comment]
Ah damn... my mistake. Deleted vendor folder article-bundle and installed again and now it works. Sorry

**Comment by nnatter** [comment]
No problem - gonna close this then 🙂
