### ISSUE TITLE
Parameter 'structureTypes' for SmartContent doesnt work for Admin-view

### ISSUE THREAD

**Issue by patrickpotthoff** [sulu/SuluArticleBundle#452]
| Q | A
| --- | ---
| Sulu Version | Sulu 2.0.3
| Browser Version | Firefox

# Actual Behavior

'structureTypes' is working fine for preview and website. Only items which are defined will get shown. Except the admin-view! All items will get shown. Seems like it the communication with the api and 'structureTypes' isnt working correctly.

'types' is working fine for preview, admin and website.

# Expected Behavior

Only items which are defined should be displayed. 

# Steps to Reproduce
Not working:
`param name="structureTypes" value="blog" `

Working:
`param name="types" value="blog"`

**Comment by niklasnatter** [comment]
Thanks for reporting! I just tested this with Sulu 2.2.3 and SuluArticleBundle 2.2.2. The following configuration works for me, therefore i am going to close this 🙂 

```xml
<property name="articles" type="smart_content">
    <meta>
        <title lang="en">Articles</title>
        <title lang="de">Artikel</title>
    </meta>

    <params>
        <param name="provider" value="articles"/>
        <param name="structureTypes" value="other"/>
    </params>
</property>
```
