### ISSUE TITLE
All articles are visible in all locales

### ISSUE THREAD

**Issue by man-andy** [sulu/SuluArticleBundle#460]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| SuluArticleBundle Version | 2.0.0-alpha3
| Sulu Version | 2.0.4

#### Actual Behavior

When creating articles in a multi locales site, all the articles are visible in every locale.

#### Expected Behavior

Do now show or add a filter to see which page is translated in the current locale.

**Comment by nnatter** [comment]
Should be fixed by #469
