### ISSUE TITLE
Article list does not display indicator for untranslated articles

### ISSUE THREAD

**Issue by nnatter** [sulu/SuluArticleBundle#462]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no

#### Actual Behavior

The article list does not display any indicator if an article is not translated to the currently selected locale. This makes it hard to see which articles are available in the current language.

![article list behaviour](https://i.imgur.com/wAHcx7z.gif)

#### Expected Behavior

The list should display a `ghost language` indicator similar to the page list or snippet list.

![snippet list behaviour](https://i.imgur.com/D8LBAcE.gif)

#### Steps to Reproduce

1. Create a new article in english
2. Navigate to the article list
3. Switch the language to german

#### Related Issues

Probably related to #460

**Comment by man-andy** [comment]
Yes, i think we want the same behaviour.

**Comment by nnatter** [comment]
Should be fixed by #469
