### ISSUE TITLE
Article list does not display indicator for draft articles

### ISSUE THREAD

**Issue by nnatter** [sulu/SuluArticleBundle#463]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no

#### Actual Behavior

The article list does not display any indicator if an article is a draft. This makes it hard to see which articles are published at the moment.

![article list behaviour](https://i.imgur.com/wAHcx7z.gif)

#### Expected Behavior

The list should display a `draft` indicator similar to the page list.

![page list behaviour](https://i.imgur.com/n7pp1wI.gif)

#### Steps to Reproduce

1. Create a new article
2. Save the article as draft only
3. Navigate to the article list

#### Related Issues

Probably related to https://github.com/sulu/sulu/issues/5225

**Comment by luca-rath** [comment]
https://github.com/sulu/sulu/pull/5348

**Comment by nnatter** [comment]
As https://github.com/sulu/sulu/pull/5348 is merged, this should be quite easy to fix now 🙂

**Comment by luca-rath** [comment]
I guess this will automatically be fixed, as soon as Sulu 2.0.9 is released

**Comment by luca-rath** [comment]
But i would wait with closing this issue until there's a release.

**Comment by nnatter** [comment]
Should be fixed now - thank you!
