### ISSUE TITLE
No article URL in the search index

### ISSUE THREAD

**Issue by martinlagler** [sulu/SuluArticleBundle#486]
| Q | A
| --- | ---
| Sulu Version | 2.1.0-RC1

# Actual Behavior

There is no URL for articles in the search index.

# Expected Behavior

Get the correct URL for the article in the search index.

# Steps to Reproduce

Use the websiteSearch with articles.

![image](https://user-images.githubusercontent.com/24388840/83652255-b35df200-a5ba-11ea-9e9e-bb798cdee8a4.png)

**Comment by niklasnatter** [comment]
Thanks for reporting! I think this should be fixed by #488
