### ISSUE TITLE
Admin list does not show translated article type.

### ISSUE THREAD

**Issue by manuxi** [sulu/SuluArticleBundle#492]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | ^2.0@dev
| Sulu Version | ^2.1.0-RC2

#### Actual Behavior

In the admin article list under type appears "sulu_article.types.articles" (While the tab shows the correct translation for the main type, "Artikel"). Same happens for another type (in my case 'product' =>  "sulu_article.types.products").

#### Expected Behavior

The translation of the type is missing. 
(Besides that I would expect that the structureTypes appear in the options to them in the list since the list is already filtered by type by the tab).

#### Steps to Reproduce

What I did is the following structure:
- article
	- blog
	- news

I created a blog.xml with key "blog" and `<tag name="sulu_article.type" type="article"/>`. (Same in news.xml).
```
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:xi="http://www.w3.org/2001/XInclude"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>blog</key>

    <view>articles/blog</view>
    <controller>Sulu\Bundle\ArticleBundle\Controller\WebsiteArticleController::indexAction</controller>
    <cacheLifetime>144000</cacheLifetime>

    <meta>
        <title lang="en">Blog</title>
        <title lang="de">Blog</title>
    </meta>

    <tag name="sulu_article.type" type="article"/>

    <properties>
        [snip]
    </properties>
</template>
```

In my config the translation is declared as follows:

```
sulu_article:
    types:
        article:
            translation_key: "sulu_article.types.articles"
        product:
            translation_key: "sulu_article.types.products"
```

The translations are located in admin.de.yml.

Screenshot:
![image](https://user-images.githubusercontent.com/11303615/84285462-cd10b380-ab3d-11ea-95b9-07e31efe41a5.png)

**Comment by alexandersch** [comment]
I am also experiencing this bug. I will investigate if I can create a PR for this issue.
