### ISSUE TITLE
Can't install bundle with clean installation of Sulu via skeleton

### ISSUE THREAD

**Issue by dekamaru** [sulu/SuluArticleBundle#499]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.0.0
| Sulu Version | 2.1.0

#### Actual Behavior

PHP 7.4 CLI
After running `composer require sulu/article-bundle` command i received next error

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sulu/article-bundle ^2.0 -> satisfiable by sulu/article-bundle[2.0.0].
    - sulu/article-bundle 2.0.0 requires symfony/config ^4.3 -> satisfiable by symfony/config[4.3.x-dev, 4.4.x-dev, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

#### Expected Behavior

Bundle installs successfully

#### Steps to Reproduce

1. Create project via skeleton `composer create-project sulu/skeleton sulu -n`
2. Install bundle `composer require sulu/article-bundle`

#### Possible Solutions

Composer.json needs to be fixed?
In release/2.0 branch symfony/config dependency requires only "^4.3" not "^4.3 || ^5.0" (Sulu 2.1 requires ^5.1 version)

**Comment by nnatter** [comment]
Hey, thanks for reporting the issue. This should already be fixed with #491. There are still some minor issues, but I am hopeful that we can release a new version including this changes soon 🙂
