### ISSUE TITLE
False webspacekey in structure

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluArticleBundle#51]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.1

#### Actual Behavior

False webspacekey in structure

#### Expected Behavior

Structure should return the current and not `articles` as webspacekey.

#### Steps to Reproduce

Content Type with following code:

```php
$webspaceKey = $property->getStructure()->getWebspaceKey();
```

#### Possible Solutions

Should get the webspaceKey from the requestAnalyzer.

**Comment by niklasnatter** [comment]
Just tested this with Sulu 2.2.3 and SuluArticleBundle 2.2.2. `property->getStructure()->getWebspaceKey()` will return `null` now. So unfortunately, this is still an issue in up-to-date versions.

**Comment by alexander-schranz** [comment]
Maybe a content type should get always the `locale` and `webspaceKey` in which the content type should be resolved. The resourceLocator Content Type for pages is maybe the only content type which need to be resolved with a the "targetWebspaceKey" (`$structure->getWebspaceKey()`), but not 100% sure.
