### ISSUE TITLE
Support live generation of resource-locator when creating article

### ISSUE THREAD

**Issue by thenetexperts** [sulu/SuluArticleBundle#514]
| Q | A
| --- | ---
| Bug? | maybe
| New Feature? | maybe
| SuluArticleBundle Version | 2.1.0
| Sulu Version | 2.2@dev

#### Actual Behavior

After installing fresh SuluArticleBundle and creating a new article, the ResourceLocator (path) is not being prefilled after adding the title. This is different behaviour learned from SuluPageBundle.
When the ResourceLocator is not being filled manually, the normal path creation will take place on article save, and thus visible in the UI when edition the created article again.

#### Expected Behavior

When entering the article's title the ResourceLocator should fill the field, making it easier to commit to the proposal or change the path.

#### Steps to Reproduce

Install SuluArticleBundle, create a new default article, fill the article's title.

#### Possible Solutions

Have not checked if this is to be fixed on admin ui side or SuluArticleBundle.

**Comment by nnatter** [comment]
Hey, thanks for reporting this! I think it would be nice to make this consistent with the behaviour inside of pages too. 

Unfortunately, I think that the routing configuration of the bundle (see [Routing section](https://github.com/sulu/SuluArticleBundle/blob/master/Resources/doc/routing.md) of the docs) is not compatible with this behaviour at the moment. The routing configuration allows to access the article object via `object`. This is not possible until the article is saved 😕

**Comment by niklasnatter** [comment]
Just for completion: ~This bundle does not support **live**-generation of the resource-locator (live update of the resource-locator when the user changes the title in the form) at the moment~ (No longer true, see comment below). But it does support automatic generation of the resource locator when the article is created.

If the resource locator input has no value when the article form is saved, the resource locator will be generated using the [configured route schema](https://github.com/sulu/SuluArticleBundle/blob/master/Resources/doc/routing.md). If you always want to generate the resource locator using the configured schema initially, you can hide the input field on the form when adding an article by using a `visibleCondition`:

```xml
<property name="routePath" type="route" visibleCondition="!!id">
    <meta>
        <title lang="en">Resourcelocator</title>
        <title lang="de">Adresse</title>
    </meta>

    <tag name="sulu_article.article_route"/>
</property>
```

**Comment by niklasnatter** [comment]
With https://github.com/sulu/sulu/pull/5675 being merged, it is now possible to configure the `SuluArticleBundle` to use live generation of the resource locator (live update of the  resource locator field in the administration interface when creating an article). The configuration also enables the `Refresh URL` button below the resource locator field:

```diff
# config/packages/sulu_article.yaml

sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            generator: schema
            options:
-               route_schema: '/articles/{object.getTitle()}'
+               route_schema: '/articles/{implode("-", object)}'
```

```diff
# config/templates/articles/default.xml

<property name="title" type="text_line" mandatory="true">
    <meta>
        <title lang="en">Title</title>
        <title lang="de">Titel</title>
    </meta>

    <params>
        <param name="headline" value="true"/>
    </params>

+   <tag name="sulu.rlp.part"/>
</property>
```

I am thinking about changing the documentation to use this configuration per default. I think this is the preferred behaviour in most cases. Unfortunately, the disadvantage of this configuration is that it is not compatible with using the `template` or `type` generator that allow to define different `route:schema`s for different types/templates (see https://github.com/sulu/SuluArticleBundle/blob/2.x/Resources/doc/routing.md#route-schema).

**Comment by niklasnatter** [comment]
Thanks for creating this! We adjusted the default configuration to use live generation in #581 🙂
