### ISSUE TITLE
Twig variable `urls` does not contain the right urls

### ISSUE THREAD

**Issue by Quehnie** [sulu/SuluArticleBundle#519]
| Q | A
| --- | ---
| Bug? | yes
| SuluArticleBundle Version | f02f4e162f38d47a7c45c5f35c6f36bf474e67d2
| Sulu Version | 229d861d93af610058e7a7374a062ee779f4b67d

#### Actual Behavior

How does Sulu behave at the moment? 

in the urls array is the locale key and just the base url for this language.

#### Expected Behavior

the array is locale as key and full url for this locale.

#### Steps to Reproduce

Create multi-language webspace and add an article in both languages, then just dump the urls variable.

**Comment by nnatter** [comment]
With #526, the `localizations` variable should now contain the correct URLs. Thanks for reporting! 🙂
