### ISSUE TITLE
URL cannot be refreshed automatically

### ISSUE THREAD

**Issue by speex404** [sulu/SuluArticleBundle#580]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.3
| Sulu Version | 2.3
#### Actual Behavior
When changing the title, the button to refresh the url remains grayed out.
<br>

#### Expected Behavior

When changing the title, the button should become active and when selecting it, the url should be refreshed.
<br>

![image](https://user-images.githubusercontent.com/29870451/121925008-c3b3bb80-cd3c-11eb-901d-31b4b06fe661.png)

**Comment by niklasnatter** [comment]
Hey,
thanks for reaching out. Refreshing an URL is only possible when using live generation (see https://github.com/sulu/SuluArticleBundle/issues/514#issuecomment-817662765).

At the moment, the default configuration of the bundle generates the URL based on the `ArticleDocument` instance after save. This allows to include things like the `id` of an article in the generated URL, but it prevents live generation. If you do not need data that is only available after save, you can change your configuration like described in https://github.com/sulu/SuluArticleBundle/issues/514#issuecomment-817662765.

**Comment by niklasnatter** [comment]
Thanks for creating this! We adjusted the default configuration to allow for refreshing in #581 🙂
