### ISSUE TITLE
Sorting of list on dates is not working properly

### ISSUE THREAD

**Issue by srdjanmis** [sulu/SuluArticleBundle#585]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.x
| Sulu Version | 2.2

#### Actual Behavior

When clicked on column Created on, or Checked On, list always sorts by Authored On column

#### Expected Behavior

When clicked on Created on, or Checked On, list should sort by clicked column.

#### Steps to Reproduce

Just add column to be visible on article list, and click on any of wrongful one.

#### Possible Solutions

Lines 174 and 179 should be corrected respectively.

**Comment by luca-rath** [comment]
Fixed by #586
