### ISSUE TITLE
hreflang tag generation broken for unpublished articles

### ISSUE THREAD

**Issue by popoplanter** [sulu/SuluArticleBundle#587]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.3.1
| Sulu Version | 2.3.0

#### Actual Behavior

In article pages an unpublished page for a localization causes the other localizations to generate hreflang tags linking to that unpuplished page. Only if the article for the localization is deleted, the hreflang tag also gets deleted. If an article is created for the first time and no other localization version for the article exists, the hreflang tags are correct.   

#### Expected Behavior

Just like in normal pages, articles should not be generating hreflang tags for unpublished articles.

#### Steps to Reproduce

create an article and a version of the same article in another language. then unpublish one of them and check the hreflang tags on the other one. it should be removed and not linking to a 404 page of the unpublished articles.

#### Possible Solutions

Fix the "alternate" in "localizations" property from true to false when unpublishing an article.

currently its like this:
![Bildschirmfoto 2021-07-22 um 16 45 39](https://user-images.githubusercontent.com/30287946/126757856-78bb357e-511a-4d7a-96c1-1ccc3255c465.png)

should be like this:
![Bildschirmfoto 2021-07-22 um 16 45 10](https://user-images.githubusercontent.com/30287946/126757866-0e3c3c26-c403-42ae-9eeb-76808f07c116.png)

**Comment by niklasnatter** [comment]
@C-burr Thanks for reporting! Could you check if #589 fixes the issue in your project?

**Comment by luca-rath** [comment]
@C-burr Should be fixed now and will be released as `2.3.2`
