### ISSUE TITLE
Extension of ArticleViewDocument

### ISSUE THREAD

**Issue by RaphaelHofer** [sulu/SuluArticleBundle#59]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | all

#### Actual Behavior

Additional properties added to ArticleViewDocument for elastic search indexing are not returned in page document.

#### Expected Behavior

return of properties in page document

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

add getContent and getRoutePath to ArticleResourceItem

**Comment by wachterjohannes** [comment]
`getRoutePath` is already present in the document. What did you like to receive from the function `getContent` @RaphaelHofer

**Comment by RaphaelHofer** [comment]
I think you already fixed that issue... 😅
