### ISSUE TITLE
ArticleDataProvider additional Sorting

### ISSUE THREAD

**Issue by Quehnie** [sulu/SuluArticleBundle#63]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

#### Actual Behavior

The function `getSearchResult` is private so there isn't a way to extend the sort when you extend from this class.

#### Expected Behavior & Possible Solutions

Some public function where you can add sort options to the search.

**Comment by wachterjohannes** [comment]
@Quehnie i think the linked PR should fix your issue without changing the visibility of the given function.

Reopen issue if not!
