### ISSUE TITLE
Symfony 6.3 annotation issue

### ISSUE THREAD

**Issue by hual7** [sulu/SuluArticleBundle#641]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Related issue | https://github.com/sulu/sulu/issues/7095, https://github.com/symfony/symfony/issues/50617
| SuluArticleBundle Version | 2.5.0
| Sulu Version | 2.5.9

#### Actual Behavior

After upgrading to Symfony 6.3 console shows a semantical error in FileLoader.php line 182:
`[Semantical Error] The annotation "@FOS\RestBundle\Controller\Annotations\Get" in method Sulu\Bundle\ArticleBundle\Controller\ArticleController::getAction() was never imported. Did you maybe forget to add a "use" statement for this annotation? in /vendor/sulu/article-bundle/Resources/config/routing_api.yml (which is being imported from "/config/routes/sulu_admin.yaml"). Make sure there is a loader supporting the "rest" type.`

and AnnotationException.php line 40:
`[Semantical Error] The annotation "@FOS\RestBundle\Controller\Annotations\Get" in method Sulu\Bundle\ArticleBundle\Controller\ArticleController::getAction() was never imported. Did you maybe forget to add a "use" statement for this annotation?`

#### Expected Behavior

It should not error.

#### Steps to Reproduce

`composer up`

**Comment by EikiProg** [comment]
I have the same type of errors with a fresh install when sulu call for admin/config

```
[Semantical Error] The annotation "@JMS\Serializer\Annotation\Groups" in property Sulu\Bundle\MarkupBundle\Markup\Link\LinkConfiguration::$title was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

**Comment by alexander-schranz** [comment]
This sounds like a BC break in Symfony or FOSRestBundle itself, so I think the issue need to be resolved there.Do you already now a upstream issue which we can link here?

**Comment by alexander-schranz** [comment]
This should now be fixed with: https://github.com/handcraftedinthealps/ElasticsearchBundle/releases/tag/5.4.1:

```bash
composer update handcraftedinthealps/ElasticsearchBundle
```
