### ISSUE TITLE
Add ElasticSearch 8 in composer.json

### ISSUE THREAD

**Issue by mortis0** [sulu/SuluArticleBundle#651]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

The bundle has a dependency on elasticsearch/elasticsearch but never use it directly, only through handcraftedinthealps/elasticsearch-bundle, so it would be nice to add elasticsearch/elasticsearch ^8 and handcraftedinthealps/elasticsearch-dsl ^8 to the composer.json

That would allow to replace only handcraftedinthealps/elasticsearch-bundle to make the article bundle work with ES 8

**Comment by alexander-schranz** [comment]
There is not yet full support for Elasticsearch 8. It requires also update the massive search bundle to support Elasticsearch 8 which is currently failing on ES8 server version.

https://github.com/sulu/SuluArticleBundle/pull/608

**Comment by mortis0** [comment]
Thanks for your answer, my point was just that as ArticleBundle do not depends directly on elasticsearc/elasticsearch, why put a require on this package in it ? In my case, we manage to work with an ES8 with some adjustements in handcraftedinthealps/elasticsearch-bundle and massive-search-bundle, and then we had to fork article-bundle just to modify its composer.json to allow ES 8
Anyway, this is just a small inconvenience, thanks for your amazing work

**Comment by alexander-schranz** [comment]
Thank you. The queries written in the article bundle are for a specific elasticsearch version. Even we not directly use the Elasticsearch Client Library. We indirectly have over the query and configured options a dependency to a specific client/server version of Elasticsearch that is why we define it here also for transparency what versions of the server are currently supported.
