### ISSUE TITLE
Article copy locale does not apply to routePath type `page_tree_route`

### ISSUE THREAD

**Issue by Quehnie** [sulu/SuluArticleBundle#661]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.5.1
| Sulu Version | Specific version or SHA of a commit

#### Actual Behavior

Create an article which uses the `page_tree_route` type as routePath.
Then copy the article into another language, in the UI it will show the right page version of the new language,
but in the `data` the route path from the old site is copied. Which results into weird urls.

/de/neuigkeiten/firmenfest -> /en/neuigkeiten/company-party 

#### Expected Behavior

Load the URL of the page with the target locale and add it into the data, if it does not exist remove the page from data and use `/`

#### Steps to Reproduce

See in Actual Behavior.

#### Possible Solutions

See in Expected Behavior

**Comment by alexander-schranz** [comment]
fixed in https://github.com/sulu/sulu/pull/7311
