### ISSUE TITLE
Automatic update slug for page_tree_route based article

### ISSUE THREAD

**Issue by Olivier127** [sulu/SuluArticleBundle#666]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.5.3 
| Sulu Version | 2.5.13

#### Actual Behavior

When you create an article with a parameterized routePath using page_tree_route, despite having route_schema in params, the slug does not update automatically like an article with a parameterized routePath using route.

#### Expected Behavior

Automatic filling of the slug according to the default schema (in sulu_route) or according to the schema specified in the XML file of the article (routePath of type page_tree_route).

#### Steps to Reproduce

Create an article with the 
[page_tree.txt](https://github.com/sulu/SuluArticleBundle/files/14614036/page_tree.txt)

put "page test" inside title section.
clic on the slug, or press tab key
The slug remains empty.

#### Possible Solutions

It seems that there is no event handling this use case. This page should have the same behavior as an article using the routePath of type route and calling the URL admin/api/routes?action=generate with the correct parameters.

**Comment by alexander-schranz** [comment]
Think this is duplicated to #667
