### ISSUE TITLE
ArticleLinkProvider and Multiple Portals

### ISSUE THREAD

**Issue by Olivier127** [sulu/SuluArticleBundle#674]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.5.3
| Sulu Version | 2.5.15

#### Actual Behavior

Using link content_type for an article use the wrong url portal.

#### Expected Behavior

ArticleLinkProvider must generate the right contextual url for an article.

#### Steps to Reproduce

This is my webspace configuration
[demo.txt](https://github.com/sulu/SuluArticleBundle/files/15073496/demo.txt)

Create an article
Create a link property on homepage and select the previous article
Go to the http://127.0.0.1
the link of the article is http://sulu/<slug of article> not http://127.0.0.1/<slug of article>

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by alexander-schranz** [comment]
You have 2 portals with the same locale inside a locale should only be part of one portal not multiple, based on the locale the portal is detected and so a locale can not be part of 2 portals. Keep in mind portal are just developer sugar, to group different localized together and great own logic on top of it. They don't exist from a content manager point of view.
