### ISSUE TITLE
New sulu:reference:refresh command fails on unpublished articles

### ISSUE THREAD

**Issue by rogamoore** [sulu/SuluArticleBundle#680]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.6.0
| Sulu Version | 2.6.2
#### Actual Behavior

Running the new sulu:reference:refresh command fails when there are unpublished articles.

```bash
bin/websiteconsole sulu:reference:refresh

Refresh snippets
----------------

    2 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]

Refresh pages
-------------

   16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]

Refresh articles
----------------

    2 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]
In StructureManager.php line 69:

  Sulu\Component\Content\Compat\StructureManager::wrapStructure(): Argument #2 ($structure) must be of type Sulu\Component\Content\Metadata\StructureMetadata, null given, called
   in ../sulu-demo/vendor/sulu/sulu/src/Sulu/Component/Content/Compat/StructureManager.php on line 54

sulu:reference:refresh [<resource-key>]
```

#### Expected Behavior

Does not fail.

#### Steps to Reproduce

- Clone https://github.com/sulu/sulu-demo and follow the setup steps
- Upgrade to Sulu 2.6.2 and SuluArticleBundle 2.6.0 following the upgrade steps

Run
```bash
bin/adminconsole sulu:reference:refresh
bin/websiteconsole sulu:reference:refresh
```
It should work fine.

Now follow these steps:
- Create new article, then save and publish - above commands still work fine
- Now set the article to unpublished - above commands will fail (website context) with the error message as described before

#### Possible Solutions

- Should unpublished articles even be included in the refresh? If not, a check should be added.
- If yes, what should be done, because it looks some data is missing. I dumped the document and it doesn't even have a title.

**Comment by alexander-schranz** [comment]
@rogamoore can you give https://github.com/sulu/sulu/pull/7461 a try and check if it did fix your issue?

**Comment by rogamoore** [comment]
@alexander-schranz I just tried and can confirm it's fixed. Thanks a lot!

**Comment by alexander-schranz** [comment]
@rogamoore Thx for testing!
