### ISSUE TITLE
Unpublished article still available on Google search results

### ISSUE THREAD

**Issue by jeffasseur** [sulu/SuluArticleBundle#682]
| Q | A
| --- | ---
| Bug? | yess
| New Feature? | no
| SuluArticleBundle Version | Specific version or SHA of a commit
| Sulu Version | Specific version or SHA of a commit

#### Actual Behavior

When an article is unpublished it is still available on the Google search results.

#### Expected Behavior

Unpublished articles should not appear in Google search results.

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by alexander-schranz** [comment]
Same as for https://github.com/sulu/SuluHeadlessBundle/issues/141#issuecomment-2209033235 we don't have any effects what Google is showing. ArticleBundle should remove the article from the Sitemap and so is not longer available for everybody. Google need to revisit to check what sites still exists and not. SuluRedirectBundle allows you to give a 410 Gone statuscode to say Url is correct but Page does not longer exists. Still 404 are normally also by google removed as soon as they checked it really does not longer exists.
