### ISSUE TITLE
phpcr:migrations:migrate failure with Symfony 7

### ISSUE THREAD

**Issue by hual7** [sulu/SuluArticleBundle#688]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.6.1
| Sulu Version | 2.6.4 with Symfony 7.1

#### Actual Behavior

`bin/adminconsole phpcr:migrations:migrate` fails because `Symfony\Component\DependencyInjection\ContainerAwareTrait` has been removed in Symfony 7.

`PHP Fatal error:  Trait "Symfony\Component\DependencyInjection\ContainerAwareTrait" not found in /Users/sulu/www/vendor/sulu/article-bundle/Resources/phpcr-migrations/Version202005151141.php on line 19`

<img width="1504" alt="Bildschirmfoto 2024-07-30 um 11 02 22" src="https://github.com/user-attachments/assets/01c775d3-65db-4cae-adbc-2a25b1ad5048">

**Comment by Cephra** [comment]
I can confirm this issue. I'm experiencing the same.

It should be solved like here: https://github.com/sulu/sulu/blob/06e994f07339dc4552ce06a0005706f38f6b38d5/src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201702021447.php#L26

**Comment by Cephra** [comment]
@hual7 Should work with the latest version!
