### ISSUE TITLE
Adding translation: Proof that the article type can't change

### ISSUE THREAD

**Issue by trickreich** [sulu/SuluArticleBundle#70]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

At the moment we don't check if the type is in the request.

#### Expected Behavior

Proof that the article type can't be different between translations.

**Comment by wachterjohannes** [comment]
@trickreich could you please add some more informations?

**Comment by trickreich** [comment]
@wachterjohannes I think we don't check the article type when we are adding a translation to an existing article. So in my opinion we should check it in the backend.

**Comment by wachterjohannes** [comment]
ok (: thats right!
