### ISSUE TITLE
Smart content type displays [object Object]

### ISSUE THREAD

**Issue by hual7** [sulu/SuluArticleBundle#703]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.6.3
| Sulu Version | 2.6.4

#### Actual Behavior

The smart content displays `[object Object]` on referenced articles.
<img width="1084" alt="Bildschirmfoto 2024-09-03 um 09 04 40" src="https://github.com/user-attachments/assets/e33c2144-26e4-4008-8ae2-9186a9029513">

#### Expected Behavior

I think there should be displayed the routePath.

**Comment by Prokyonn** [comment]
> I think there should be displayed the routePath.

The smart content for articles did never show additional information, as far as I know this is only possible with a custom implementation


fixed in #708

Thank you for reporting the issue 😃
